### ISSUE TITLE
当前版本中两个小问题

### ISSUE THREAD

**Issue by zR00t1** [oubingbing/school_wechat#3]
一、所有onShareAppMessage事件中的图片URL都是引用的之前的域名下的文件，现在已经访问不到了，就导致分享给其他人小程序的时候不显示封面
![image](https://user-images.githubusercontent.com/46400438/69839786-fd74bc80-1293-11ea-8ab3-77701471bd14.png)
![image](https://user-images.githubusercontent.com/46400438/69839801-0a91ab80-1294-11ea-91e5-190d58e3774e.png)
希望叶子哥百忙之中可以把图片分享一下，毕竟还是叶子哥的图片更符合小程序整体的风格，哈哈哈哈哈
二、最新版本中的pages/personal/路径下没有letter相关文件，但是在上一个版本中是有的，缺失letter文件会在【我的】页面遇到【联系客服】功能异常的问题，遇到该问题的朋友在上个版本中找相关文件就可以了。
![image](https://user-images.githubusercontent.com/46400438/69840297-01a1d980-1296-11ea-8c94-d00684ac5410.png)

**Comment by oubingbing** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Monarch3"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 中午12:35
收件人:&nbsp;"oubingbing/school_wechat"<school_wechat@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[oubingbing/school_wechat] 当前版本中两个小问题 (#3)




一、所有onShareAppMessage事件中的图片URL都是引用的之前的域名下的文件，现在已经访问不到了，就导致分享给其他人小程序的时候不显示封面
 
 
 希望叶子哥百忙之中可以把图片分享一下，毕竟还是叶子哥的图片更符合小程序整体的风格，哈哈哈哈哈
 二、最新版本中的pages/personal/路径下没有letter相关文件，但是在上一个版本中是有的，缺失letter文件会在【我的】页面遇到【联系客服】功能异常的问题，遇到该问题的朋友在上个版本中找相关文件就可以了。
