### ISSUE TITLE
前端无法上传图片

### ISSUE THREAD

**Issue by DGuang21** [oubingbing/school_wechat#5]
![Image](https://s2.ax1x.com/2019/12/15/QfE2WQ.jpg)
叶子哥，全部操作都做好之后，无法上传图片是什么回事啊

**Comment by DGuang21** [comment]
七牛上传提示：
incorrect region, please use up-z0.qiniup.com
貌似是因为上传地址更新了导致上传失败了

**Comment by oubingbing** [comment]
把.env的这个参数填上你的七牛域名就行了QI_NIU_DOMAIN=
